/*
 * brackets-roole-autocompile
 * https://github.com/chrisenytc/brackets-roole-autocompile
 *
 * Copyright (c) 2013 Christopher EnyTC
 * Licensed under the MIT license.
 */

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4,
maxerr: 50, node: true */
/*global */

(function () {
    "use strict";

    var roole = require("roole");
    var path = require("path");
    var fs = require("fs");

    // compile the given roole file
    function compile(rooleFile, cssFile) {

        // read roole input
        fs.readFile(rooleFile, "utf-8", function (err, data) {
            if (err) {
                console.error(err);
                return;
            }

            roole.compile(data, function (err, css) {
                if (err) {
                    console.error('ErrorType: ' + err.name + ' - ' + err.message + ' on line ' + err.line);
                    return;
                } else {
                    var fileHeader = "/* Generated by roole " + roole.version + " */",
                        content = [fileHeader, css].join("\n");
                    //write css output
                    fs.writeFileSync(cssFile, content);
                }
            });

        });
    }

    function init(DomainManager) {
        if (!DomainManager.hasDomain("RooleCompiler")) {
            DomainManager.registerDomain("RooleCompiler", {
                major: 1,
                minor: 0
            });
        }
        DomainManager.registerCommand(
            "RooleCompiler", // domain name
            "compile", // command name
            compile, // command handler function
            true, // this command is asynchronous
            "Compiles a roole file", ["roolePath", "cssPath"], // path parameters
            null);
    }

    exports.init = init;

}());